name: Unit Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      spanner:
        image: gcr.io/cloud-spanner-emulator/emulator
        ports:
          - 9010:9010
          - 9020:9020
          
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test 
